INTEGER, PARAMETER :: LONG = SELECTED_INT_KIND(15)
INTEGER :: i, N
REAL (16):: FACTORIAL
READ(*,*) N
FACTORIAL = 1.q0
DO i = 1,N
FACTORIAL = FACTORIAL * i
END DO
WRITE(*,*) N, "! = ", FACTORIAL
END PROGRAM
